Add connection prometheus with tls configuration
nbycomp/nearbyone-examples pull request #13
Opened 2023-11-10 11:46 UTC by fulviodenza

This feature adds an example for connections pointing to a prometheus instance protected by (m)TLS.

2023-11-13 08:45 UTC, alvarovn requested changes

2023-11-13 08:45 UTC, alvarovn commented on examples/OktoResources/ResourceRelations/Connection/06.external-target-prometheus-connection-tls-config.yaml
> +            key: | {{ .Values.prometheus.endpoint.clientKey | nindent 14 }}
Let's make an example for a prometheus config with this. Let's not use {{ .Values... }} there, and use throwaway certs.

2023-11-13 09:27 UTC, alvarovn commented on examples/OktoResources/ResourceRelations/Connection/06.external-target-prometheus-connection-tls-config.yaml
> +            key: | {{ .Values.prometheus.endpoint.clientKey | nindent 14 }}
To clear up ambiguity: Let's make a prometheus config typed connection instead. The external target doesn't get directly affected by this.

2023-11-13 16:12 UTC, alvarovn commented on examples/OktoResources/ResourceRelations/Connection/07.prometheus-config-connection.yaml
> +    kind: K8sCluster
We can remove the labels

2023-11-13 16:12 UTC, alvarovn commented on examples/OktoResources/ResourceRelations/Connection/07.prometheus-config-connection.yaml
It's missing the connection type.

2023-11-13 16:13 UTC, alvarovn commented on examples/OktoResources/ResourceRelations/Connection/06.external-target-prometheus-connection-tls-config.yaml
I don't think we need this connection in the examples.

2023-11-14 08:43 UTC, fulviodenza commented on examples/OktoResources/ResourceRelations/Connection/06.external-target-prometheus-connection-tls-config.yaml
removed

2023-11-14 08:43 UTC, fulviodenza commented on examples/OktoResources/ResourceRelations/Connection/07.prometheus-config-connection.yaml
Added

2023-11-14 08:43 UTC, fulviodenza commented on examples/OktoResources/ResourceRelations/Connection/07.prometheus-config-connection.yaml
> +    kind: K8sCluster
removed

2023-11-14 09:08 UTC, alvarovn approved these changes
LGTM, le'ts squash and merge ASAP

2023-11-14 10:03 UTC, merged